package uk.co.robincsmith.stringops;

import static org.junit.Assert.*;

import java.util.Arrays;
import java.util.Collection;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

/**
 * Tests the replacePatternWithHyphens() method of the StringHelper class. Uses
 * parametrised testing.
 * @author Robin Smith
 */
@RunWith(Parameterized.class)
public class StringHelperTestReplacePatternWithHyphens
{
    private StringHelper sh = new StringHelper();
    
    // Parameters
    private String input;
    private String pattern;
    private String expectedOutput;
    
    /**
     * Constructor for the test cases. Parameters are generated by
     * generateParameters().
     * @param input Input for the test case
     * @param pattern The pattern to be replaced with hyphens
     * @param expectedOutput Expected resultant String for comparison
     */
    public StringHelperTestReplacePatternWithHyphens(String input,
                                                     String pattern,
                                                     String expectedOutput)
    {
        super();
        this.input = input;
        this.pattern = pattern;
        this.expectedOutput = expectedOutput;
    }

    /**
     * Generate the parameters used by the test cases.
     * @return A collection of input/pattern/expectedOutput arrays to be passed
     * to the constructor each time a test case is run
     */
    @Parameters
    public static Collection<String[]> generateParameters()
    {
        String[][] parameters = {
        // Test pattern appearing once at beginning, middle and end.
                                  {"abcdeh", "ab", "--cdeh"},
                                  {"abcdeg", "cd", "ab--eg"},
                                  {"abcdef", "ef", "abcd--"},
        // Test pattern appearing multiple times, in a variety of positions.
                                  {"abcdefab", "ab", "--cdef--"},
                                  {"abababab", "ab", "--------"},
                                  {"cabababd", "ab", "c------d"},
        // Test pattern not appearing, string unchanged
                                  {"abcdefabc", "abd", "abcdefabc"},
        // Test empty string
                                  {"", "ab", ""},
        // Test empty pattern
                                  {"abab", "", "abab"},
        };
        return Arrays.asList(parameters);
    }
    
    /**
     * The test to be run in each test case. Parameters are set in the
     * constructor.
     */
    @Test
    public void test()
    {
        assertEquals(expectedOutput, 
                     sh.replacePatternWithHyphens(pattern, input));
    }

}
